sudo: false
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - jruby-9.0
  - jruby-1.7
  - jruby-18mode
  - jruby-19mode
  - rbx-2
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
  - openjdk6
matrix:
  exclude:
    - rvm: 1.8.7
      jdk: openjdk7
    - rvm: 1.8.7
      jdk: oraclejdk7
    - rvm: 1.8.7
      jdk: oraclejdk8
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 1.9.3
      jdk: oraclejdk8
    - rvm: 2.0
      jdk: openjdk7
    - rvm: 2.0
      jdk: oraclejdk7
    - rvm: 2.0
      jdk: oraclejdk8
    - rvm: 2.1
      jdk: openjdk7
    - rvm: 2.1
      jdk: oraclejdk7
    - rvm: 2.1
      jdk: oraclejdk8
    - rvm: 2.2
      jdk: openjdk7
    - rvm: 2.2
      jdk: oraclejdk7
    - rvm: 2.2
      jdk: oraclejdk8
    - rvm: rbx-2
      jdk: openjdk7
    - rvm: rbx-2
      jdk: oraclejdk7
    - rvm: rbx-2
      jdk: oraclejdk8
script: ./run-benchmarks.sh
